# Logging and Output arguments
log_level: info
logging_strategy: steps
logging_steps: 100
report_to:
- tensorboard
- wandb
save_strategy: steps
save_steps: 100
output_dir: data/Doge-60M
overwrite_output_dir: true
push_to_hub: true
private: true
# token: <your-token>
hub_model_id: Doge-60M
hub_strategy: every_save

# Model arguments
model_config:
  vocab_size: 32768
  hidden_size: 512
  intermediate_size: 1024
  num_hidden_layers: 16
  hidden_dropout: 0.0
  hidden_act: "silu"
  use_cache: True
  tie_word_embeddings: True
  max_position_embeddings: 2048
  rope_theta: 10000.0
  rope_scaling:
    rope_type: dynamic
    factor: 4.0
    original_max_position_embeddings: 2048
  num_attention_heads: 4
  num_key_value_heads: 2

model_name_or_path: SmallDoge/Doge-60M
torch_dtype: bfloat16

# Data training arguments
dataset_name: ./datasets/pt_dataset
dataset_configs:
- all

# PT trainer arguments
preprocessing_num_workers: 1 # Equal to the number of GPUs you are using
seed: 233
do_train: True
max_steps: 16000
per_device_train_batch_size: 1
do_eval: True
eval_strategy: steps
eval_steps: 100
per_device_eval_batch_size: 1
optim: adamw_torch_fused
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-8
learning_rate: 6.0e-3
lr_scheduler_type: warmup_stable_decay
lr_scheduler_kwargs:
  warmup_type: linear
  decay_type: linear
  num_decay_steps: 1600
  min_lr_ratio: 0.0
warmup_steps: 1600
weight_decay: 0.01
gradient_accumulation_steps: 512
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
max_grad_norm: 1.0
bf16: True
