compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  offload_optimizer:
    device: cpu
    pin_memory: true
  offload_param:
    device: cpu
  train_batch_size: auto
  train_micro_batch_size_per_gpu: auto
  gradient_accumulation_steps: auto
  train_batch_size: 32  # 4 * 8 (per_device_batch_size * gradient_accumulation_steps)
  train_micro_batch_size_per_gpu: 1  
  gradient_accumulation_steps: 32  
  bf16:
    enabled: true  
  optimizer:
    type: AdamW
    params:
      lr: 5.0e-5  
      betas: [0.9, 0.999]
      eps: 1e-8
      weight_decay: 0.0001  
      bias_correction: true
main_process_port: 29500
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
