# Logging and Output arguments
log_level: info
logging_strategy: steps
logging_steps: 100
report_to:
- tensorboard
- wandb
save_strategy: "no"
output_dir: data/Doge-320M
overwrite_output_dir: true
push_to_hub: true
private: true
# token: <your-token>
hub_model_id: Doge-320M
hub_strategy: every_save

# Model arguments
mmodel_config:
  vocab_size: 32768
  hidden_size: 1024
  intermediate_size: 2048
  num_hidden_layers: 32
  hidden_dropout: 0.0
  hidden_act: "silu"
  use_cache: True
  tie_word_embeddings: True
  max_position_embeddings: 2048
  rope_theta: 10000.0
  rope_scaling:
    rope_type: dynamic
    factor: 4.0
    original_max_position_embeddings: 2048
  num_attention_heads: 8
  num_key_value_heads: 4

model_name_or_path: SmallDoge/Doge-320M
torch_dtype: bfloat16

# Data training arguments
dataset_name: ./datasets/pt_dataset
dataset_configs:
- all
preprocessing_num_workers: 8

# PT trainer arguments
seed: 233
do_train: True
max_train_steps: 32000
per_device_train_batch_size: 1
do_eval: True
eval_strategy: steps
eval_steps: 100
per_device_eval_batch_size: 1
optim: adamw_torch_fused
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-8
learning_rate: 2.0e-3
lr_scheduler_type: warmup_stable_decay
lr_scheduler_kwargs:
  warmup_type: linear
  decay_type: linear
  num_decay_steps: 3200
  min_lr_ratio: 0.0
warmup_steps: 3200
weight_decay: 0.01
gradient_accumulation_steps: 1024
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
max_grad_norm: 1.0
bf16: True
